version: '2.1'

services:
  probate-frontend:
    # build:
    #   context: ../.
    # image: probate/probabte-frontend
    image: docker.artifactory.reform.hmcts.net/probate/probate-frontend:${FRONTEND_TAG:-latest}
    container_name: probate-frontend
    environment:
      - USE_HTTPS=false
      - USE_AUTH=false
      - USE_IDAM=false
      - VALIDATION_SERVICE_URL=http://business-service:8081/validate
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 3000:3000
    links:
     - business-service
    depends_on:
     - business-service
    networks:
      default:
        aliases:
          - https://www-local.probate.reform.hmcts.net

  business-service:
    image: docker.artifactory.reform.hmcts.net/probate/business-service
    container_name: business-service
    environment:
      - SERVER_PORT=8881
      - http_proxy=
      - https_proxy=
      - no_proxy=
    ports:
     - 8881:8881

  probate-postfix:
    image: catatnight/postfix
    container_name: probate-postfix
    environment:
        - maildomain=localhost
        - smtp_user=localhost:Pr0bate!23
    ports:
      - 25:25
