nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    FEATURE_TOGGLES_API_URL: http://${SERVICE_NAME}-ftr-tgl-api
    REDIS_HOST: ${SERVICE_NAME}-redis-master
    REDIS_PORT: 6379
    REDIS_USE_TLS: false
  keyVaults:
    probate:
      secrets:
        - idam-s2s-secret
        - ccidam-idam-api-secrets-probate
        - postcode-service-url
        - postcode-service-token2
        - probate-survey
        - probate-survey-end
        - probate-application-fee-code
        - probate-uk-application-fee-code
        - probate-overseas-application-fee-code
        - probate-service-id
        - probate-site-id
        - caveat-user-name
        - caveat-user-password
        - probate-webchat-id
        - probate-webchat-tenant
        - probate-webchat-button-no-agents
        - probate-webchat-button-busy
        - probate-webchat-button-service-closed
        - payCaseWorkerUser
        - payCaseWorkerPass
        - google-analytics-tracking-id
rpe-feature-toggle-api:
  enabled: true
  releaseNameOverride: ${SERVICE_NAME}-ftr-tgl-api
  java:
    releaseNameOverride: ${SERVICE_NAME}-ftr-tgl-api
    ingressIP: ${INGRESS_IP}
    consulIP: ${CONSUL_LB_IP}
    postgresql:
      enabled: true # for rpe-feature-toggle-api
      image:
        tag: '11.3.0'
    registerAdditionalDns:
      enabled: true
      primaryIngressHost: ${SERVICE_FQDN}
      prefix: ftr-tgl
    environment:
      EDITOR_USERNAME_TEST: editor@example.com
      EDITOR_PASSWORD_TEST: Password12
    importer:
      cron:
        enabled: false
      oneoff:
        enabled: false
redis:
  enabled: true
idam-pr:
  enabled: true
  redirect_uris:
    Probate:
      - https://${SERVICE_FQDN}/oauth2/callback
